### ISSUE TITLE
No support for aarch64

### ISSUE THREAD

**Issue by swelborn** [Kuyoh/docker-vcpkg#86]
Hello! This package looks great. I have gotten a start on adding aarch64 support for it, as when you pull on mac silicon you have to specify `--platform=linux/amd64`. I have gotten a start that will suit my purposes on this branch: https://github.com/swelborn/docker-vcpkg/tree/aarch64. This works for me so far, as I think only cmake tars are dependent on the architecture. I will let you know if I come across any trouble.

I don't have time to set up the github actions for this, but if you want to use this please feel free. I'm not sure of the status of GHA M1 runners...

**Comment by Kuyoh** [comment]
Thank you!
I don't have the hardware to test myself, but your changes look very reasonable.
i'll incorporate them and try to get github actions to test it :D

**Comment by Kuyoh** [comment]
Looks like there is m1 support, but the runner is not available for free.

For now i'll incorporate your script changes without messing the github actions.
Hopefully there's free options in the future.

**Comment by Kuyoh** [comment]
@swelborn i merged your changes, but i'd assume that the other binaries will work if they're not built for aarch64. Could you try pulling the latest version?

**Comment by Kuyoh** [comment]
I ended up using qemu for the build. It makes the builds quite slow, but it looks like it works.

**Comment by Kuyoh** [comment]
The arm64 version was published. Closing this issue. If you find problems when using it, please open a new one.
