### ISSUE TITLE
Unable to provide overrides

### ISSUE THREAD

**Issue by swelborn** [Kuyoh/docker-vcpkg#90]
If you use "builtin_baseline" with overrides:

```
  "builtin-baseline": "3426db05b996481ca31e95fff3734cf23e0f51bc",
  "overrides": [
    {
      "name": "zlib",
      "version": "1.2.8"
    }
```

You get an error on vcpkg install. This is because the baseline is checked against the git repo info, which is not included in the releases. Would it be more effective to use:
```
git clone https://github.com/microsoft/vcpkg.git && git checkout tags/${VCPKG_VERSION}
```
?

**Comment by Kuyoh** [comment]
I'd prefer to not have the entire repository in the image, but i can see the value in this suggestion.
Currently, doing a full clone will add 100MB to the image, though. And that number is only going to increase.

We could do a shallow clone to limit the size, although not sure what depth would be suitable. The repository has 20k commits currently. Do you think a depth of 1k would be sufficient to cover your use-case ?

**Comment by Kuyoh** [comment]
should be fixed in the next update
